#!/usr/bin/env node
/**
 * Generate historical demonstration data.
 *
 * Runs several scenarios headless through the *real* navigation pipeline and
 * records the results, so the analytics screens have meaningful history the
 * first time anyone opens them.
 *
 * Nothing here fabricates plausible-looking numbers: every row is produced by
 * the same engines that run the live demonstration. Data that was invented
 * would be indistinguishable on screen from data that was earned, which is
 * exactly the confusion this platform exists to prevent.
 *
 * Usage:
 *   node scripts/generate_demo_data.js                  # the default set
 *   node scripts/generate_demo_data.js SCN_03 SCN_15    # named scenarios
 *   node scripts/generate_demo_data.js --all            # every scenario
 *   node scripts/generate_demo_data.js --clean          # remove previous runs first
 */

import { runScenarioHeadless } from '../backend/src/simulation/engine.js';
import { getScenarioDefinition, scenarioCatalog, getConfig } from '../backend/src/config/index.js';
import { recorder } from '../backend/src/services/recorder.js';
import { performanceService } from '../backend/src/services/performanceService.js';
import { one, query, closePool } from '../backend/src/db/pool.js';
import { migrate } from '../backend/src/db/migrate.js';
import { createLogger } from '../backend/src/utils/logger.js';

const log = createLogger('generate-demo-data');

/** Scenarios generated by default: enough to make every screen meaningful. */
const DEFAULT_SET = [
  'SCN_01_HEALTHY',
  'SCN_02_GNSS_JUMP',
  'SCN_03_GRADUAL_DRAG',
  'SCN_04_JAMMING',
  'SCN_09_GNSS_RECOVERY',
  'SCN_10_MULTIPLE_FAILURE',
  'SCN_15_SAFEEN_DEMO'
];

function parseArgs(argv) {
  const args = argv.slice(2);
  return {
    all: args.includes('--all'),
    clean: args.includes('--clean'),
    scenarios: args.filter((a) => !a.startsWith('--'))
  };
}

/** Resolve a possibly abbreviated scenario id. */
function resolveScenarioId(input) {
  const exact = getScenarioDefinition(input);
  if (exact) return exact.id;
  const partial = scenarioCatalog.filter((s) => s.id.toUpperCase().includes(input.toUpperCase()));
  if (partial.length === 1) return partial[0].id;
  if (partial.length > 1) {
    throw new Error(`"${input}" is ambiguous: ${partial.map((s) => s.id).join(', ')}`);
  }
  throw new Error(`Unknown scenario "${input}". Available: ${scenarioCatalog.map((s) => s.id).join(', ')}`);
}

/**
 * Run one scenario headless and record every epoch.
 * @returns {Promise<{ runId: string, epochs: number, summary: object }>}
 */
async function generate(scenarioId) {
  const scenario = getScenarioDefinition(scenarioId);
  const started = Date.now();

  const run = await one(
    `INSERT INTO scenario_runs (scenario_id, run_label, state, seed, speed_multiplier, ins_enabled,
                                config_snapshot, notes)
     VALUES ($1, $2, 'RUNNING', $3, 0, $4, $5, $6) RETURNING id`,
    [
      scenario.id,
      'Generated demonstration data',
      scenario.seed,
      scenario.ins_enabled !== false,
      JSON.stringify({
        requirements: getConfig().requirements,
        gnss_integrity: getConfig().gnss_integrity,
        integrity: getConfig().integrity,
        fusion: getConfig().fusion
      }),
      'Produced headless by scripts/generate_demo_data.js through the same navigation pipeline as a live run.'
    ]
  );

  recorder.start(run.id);
  log.info('generating', { scenario_id: scenario.id, duration_s: scenario.duration_s });

  let epochs = 0;
  const { engine, outputs, truths } = runScenarioHeadless(scenario, {
    onEpoch: (output, truth) => {
      epochs += 1;
      recorder.recordNavigationSolution(output);
      recorder.recordGnssTrust(output);
      recorder.recordSensorHealth(output);
      recorder.recordResiduals(output);
      if (truth) recorder.recordGroundTruth(truth);
    }
  });

  // Alarms and mode transitions accumulated during the run.
  const alarms = engine.pipeline.drainAlarms();
  for (const alarm of alarms) {
    await query(
      `INSERT INTO alarms (run_id, code, severity, source, message, reason, recommended_action, sim_time_s, detail)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
      [
        run.id,
        alarm.code,
        alarm.severity ?? getConfig().alarms.severity_for?.[alarm.code] ?? 'ADVISORY',
        alarm.source,
        alarm.message,
        alarm.reason,
        alarm.recommended_action,
        alarm.sim_time_s,
        JSON.stringify(alarm.detail ?? {})
      ]
    );
  }
  for (const transition of engine.pipeline.modeManager.transitions) {
    recorder.recordModeTransition(transition);
  }
  for (const event of engine.drainEvents()) recorder.recordScenarioEvent(event);

  await recorder.stop();
  await query(
    `UPDATE scenario_runs SET state='COMPLETED', ended_at=now(), duration_s=$2 WHERE id=$1`,
    [run.id, engine.time]
  );

  const report = await performanceService.generateAndStore(run.id, null);
  const elapsed = ((Date.now() - started) / 1000).toFixed(1);

  log.info('generated', {
    scenario_id: scenario.id,
    run_id: run.id,
    epochs,
    alarms: alarms.length,
    mode_transitions: engine.pipeline.modeManager.transitions.length,
    wall_clock_s: elapsed,
    mean_error_m: report.summary.actual_error.mean_m,
    p95_error_m: report.summary.actual_error.p95_m,
    requirement_met_pct: report.summary.requirement_met_pct,
    misleading_information_pct: report.summary.misleading_information_pct,
    compliance: report.summary.compliance_result
  });

  return { runId: run.id, epochs, summary: report.summary, truths: truths.length };
}

async function main() {
  const args = parseArgs(process.argv);
  await migrate({ drop: false });

  if (args.clean) {
    log.warn('removing previously generated runs');
    await query("DELETE FROM scenario_runs WHERE run_label = 'Generated demonstration data'");
  }

  const ids = args.all
    ? scenarioCatalog.map((s) => s.id)
    : args.scenarios.length > 0
      ? args.scenarios.map(resolveScenarioId)
      : DEFAULT_SET;

  const results = [];
  for (const id of ids) {
    results.push(await generate(id));
  }

  const overall = await performanceService.overallSummary();
  log.info('complete', {
    runs: results.length,
    total_epochs: results.reduce((a, r) => a + r.epochs, 0),
    overall
  });

  // A short human-readable summary, since this is usually run by hand.
  process.stdout.write('\nGenerated demonstration runs:\n');
  for (const result of results) {
    const s = result.summary;
    process.stdout.write(
      `  ${s.scenario_id.padEnd(24)} mean ${String(s.actual_error.mean_m).padStart(6)} m · ` +
        `p95 ${String(s.actual_error.p95_m).padStart(6)} m · ` +
        `requirement met ${String(s.requirement_met_pct).padStart(6)} % · ` +
        `misleading ${String(s.misleading_information_pct).padStart(5)} %\n`
    );
  }
  process.stdout.write('\nOpen the Performance screen to explore them.\n\n');
}

main()
  .then(async () => {
    await closePool();
    process.exit(0);
  })
  .catch(async (err) => {
    log.fatal('generation failed', err);
    await closePool().catch(() => {});
    process.exit(1);
  });
